spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    # h2 database
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:h2:file:./database/nestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # mysql
    # data-source-class-name: org.mariadb.jdbc.MariaDbDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/nestdb
    username: nest
    password: "!nest#12"
    connection-timeout: 3000
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      # ddl-auto: create
      ddl-auto: validate
server:
  port: 9090
  context-path: /nest
  tomcat:
    uri-encoding: UTF-8
application:
  allows-anonymous-access: true
