server:
  port: 9090
  context-path: "/nest"
  tomcat:
    uri-encoding: utf-8
spring:
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  datasource:
    pool-name: "hikari-db-pool"
    url: "jdbc:mariadb://localhost:3306/nestdb"
    username: "nest"
    password: "!nest#12"
    hikari.data-source-class-name: org.mariadb.jdbc.MySQLDataSource
    hikari.maximum-pool-size: 20
    hikari.connection-timeout: 10
    hikari.max-lifetime: 1800000
    hikari.cache-prep-stmts: true
    hikari.prep-stmt-cache-size: 250
    hikari.prep-stmt-cache-sql-limit: 2048
    hikari.connection-test-query: select 1
security:
  basic:
    enabled: false
